---
   - name: Install all packages
     apt: name={{ item }} update_cache=yes state=present
     with_items:
        - nginx
        - apache2
        - php7.0
        - libapache2-mod-php7.0
        - php7.0-mbstring
        - libapache2-mpm-itk
        - php7.0-xml
        - unzip
        - mysql-server
        - mysql-client
        - python-mysqldb
        - sendmail

